# Generated by Django 3.0.8 on 2020-07-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=5)),
                ('quantity', models.DecimalField(decimal_places=15, max_digits=30)),
                ('bought_in_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bought_in_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
