# Generated by Django 3.0.8 on 2022-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCoinsExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.TextField()),
            ],
        ),
    ]
